/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current tenant context */
        get: operations["getTenantMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deals */
        get: operations["listDeals"];
        put?: never;
        /** Create a deal */
        post: operations["createDeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get deal by ID */
        get: operations["getDeal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update deal fields */
        patch: operations["updateDeal"];
        trace?: never;
    };
    "/v1/deals/{dealId}/truth-dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get truth dashboard for a deal
         * @description Returns aggregated claim statistics and paginated claims for the deal's truth dashboard. Provides summary counts by grade and verdict, fatal defect count, and claims list.
         */
        get: operations["getDealTruthDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents for a deal */
        get: operations["listDealDocuments"];
        put?: never;
        /**
         * Attach a document (upload metadata or provide external link)
         * @description Creates a DocumentArtifact record and (optionally) starts ingestion. Raw file upload is typically performed using pre-signed URLs or a dedicated upload endpoint.
         */
        post: operations["createDealDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{docId}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger ingestion for a document */
        post: operations["ingestDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List claims for a deal */
        get: operations["listDealClaims"];
        put?: never;
        /** Create/Propose a claim */
        post: operations["createClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claimId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get claim by ID */
        get: operations["getClaim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update claim (e.g., human verification or correction) */
        patch: operations["updateClaim"];
        trace?: never;
    };
    "/v1/claims/{claimId}/sanad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sanad chain for a claim */
        get: operations["getClaimSanad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/defects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List defects for a deal */
        get: operations["listDealDefects"];
        put?: never;
        /** Create a defect for a deal */
        post: operations["createDefect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claimId}/defects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List defects for a claim */
        get: operations["listClaimDefects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/defects/{defect_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get defect by ID */
        get: operations["getDefect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/defects/{defect_id}/waive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Waive a defect with actor and reason */
        post: operations["waiveDefect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/defects/{defect_id}/cure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cure a defect with actor and reason */
        post: operations["cureDefect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/sanads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sanads for a deal */
        get: operations["listDealSanads"];
        put?: never;
        /** Create a sanad for a deal */
        post: operations["createSanad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sanads/{sanad_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sanad by ID */
        get: operations["getSanad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a sanad */
        patch: operations["updateSanad"];
        trace?: never;
    };
    "/v1/sanads/{sanad_id}/corroboration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set corroboration for a sanad and re-compute grade */
        post: operations["setSanadCorroboration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/calcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deterministic calculation runs for a deal */
        get: operations["listDealCalcs"];
        put?: never;
        /** Run deterministic calculation engine */
        post: operations["runCalc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an IDIS pipeline run (snapshot or full) */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run status */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/debate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start LangGraph debate session (full analysis path) */
        post: operations["startDebate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/debate/{debateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get debate session (transcript + decisions) */
        get: operations["getDebate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/human-gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List human verification gates for a deal */
        get: operations["listHumanGates"];
        put?: never;
        /** Submit a human verification action (approve/correct/reject) */
        post: operations["submitHumanGateAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a partner override (e.g., allow IC export with caveats) */
        post: operations["createOverride"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deals/{dealId}/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deliverables generated for a deal */
        get: operations["listDeliverables"];
        put?: never;
        /** Generate a deliverable (snapshot/memo/truth_dashboard pack) */
        post: operations["generateDeliverable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query audit events */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available integrations and connection status */
        get: operations["listIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create webhook subscription */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example bad_request */
            code: string;
            /** @example Invalid field: deal.name */
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** @example req_123 */
            request_id?: string;
        };
        TenantContext: {
            /** Format: uuid */
            tenant_id: string;
            name: string;
            /** @example Asia/Qatar */
            timezone: string;
            /** @example me-south-1 */
            data_region: string;
        };
        /** @enum {string} */
        DealStatus: "NEW" | "INTAKE" | "SCREENING" | "DEEP_DIVE" | "IC_READY" | "DECLINED" | "ARCHIVED";
        /** @enum {string} */
        DealStage: "SEED" | "SERIES_A" | "SERIES_B" | "GROWTH" | "LATER" | "OTHER";
        /** @enum {string} */
        Materiality: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** @enum {string} */
        SanadGrade: "A" | "B" | "C" | "D";
        /** @enum {string} */
        CorroborationLevel: "AHAD" | "MUTAWATIR";
        /** @enum {string} */
        ClaimVerdict: "VERIFIED" | "INFLATED" | "CONTRADICTED" | "UNVERIFIED" | "SUBJECTIVE";
        /** @enum {string} */
        ClaimAction: "NONE" | "REQUEST_DATA" | "FLAG" | "RED_FLAG" | "HUMAN_GATE" | "PARTNER_OVERRIDE_REQUIRED";
        /** @enum {string} */
        DefectSeverity: "FATAL" | "MAJOR" | "MINOR";
        Deal: {
            /** Format: uuid */
            deal_id: string;
            name: string;
            company_name: string;
            status: components["schemas"]["DealStatus"];
            stage: components["schemas"]["DealStage"];
            tags?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateDealRequest: {
            name: string;
            company_name: string;
            stage?: components["schemas"]["DealStage"];
            tags?: string[];
            external_refs?: {
                [key: string]: unknown;
            };
        };
        UpdateDealRequest: {
            status?: components["schemas"]["DealStatus"];
            stage?: components["schemas"]["DealStage"];
            tags?: string[];
        };
        DocumentArtifact: {
            /** Format: uuid */
            doc_id: string;
            /** Format: uuid */
            deal_id: string;
            /** @enum {string} */
            doc_type: "PITCH_DECK" | "FINANCIAL_MODEL" | "DATA_ROOM_FILE" | "TRANSCRIPT" | "TERM_SHEET" | "OTHER";
            title: string;
            source_system: string;
            version_id: string;
            /** Format: date-time */
            ingested_at: string;
            sha256?: string;
            uri?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        CreateDocumentRequest: {
            doc_type: components["schemas"]["DocumentArtifact"]["doc_type"];
            title: string;
            /** @example DocSend */
            source_system?: string;
            /** @description External link or object storage uri */
            uri?: string;
            sha256?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** @default true */
            auto_ingest: boolean;
        };
        Quantity: {
            value: number;
            unit: string;
            currency?: string | null;
            /** Format: date */
            as_of?: string | null;
            time_window?: {
                label?: string;
                /** Format: date */
                start_date?: string | null;
                /** Format: date */
                end_date?: string | null;
            } | null;
        };
        Claim: {
            /** Format: uuid */
            claim_id: string;
            /** Format: uuid */
            deal_id: string;
            /** @enum {string} */
            claim_class: "FINANCIAL" | "TRACTION" | "MARKET_SIZE" | "COMPETITION" | "TEAM" | "LEGAL_TERMS" | "TECHNICAL" | "OTHER";
            claim_text: string;
            predicate?: string | null;
            value?: components["schemas"]["Quantity"];
            /** Format: uuid */
            sanad_id?: string | null;
            claim_grade: components["schemas"]["SanadGrade"];
            corroboration: {
                level: components["schemas"]["CorroborationLevel"];
                independent_chain_count: number;
            };
            claim_verdict: components["schemas"]["ClaimVerdict"];
            claim_action: components["schemas"]["ClaimAction"];
            defect_ids?: string[];
            materiality?: components["schemas"]["Materiality"];
            /** @default false */
            ic_bound: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateClaimRequest: {
            claim_class: components["schemas"]["Claim"]["claim_class"];
            claim_text: string;
            predicate?: string;
            value?: components["schemas"]["Quantity"];
            evidence_ids?: string[];
            materiality?: components["schemas"]["Materiality"];
            /** @default false */
            ic_bound: boolean;
        };
        UpdateClaimRequest: {
            claim_text?: string;
            value?: components["schemas"]["Quantity"];
            claim_verdict?: components["schemas"]["ClaimVerdict"];
            claim_action?: components["schemas"]["ClaimAction"];
            human_verified?: boolean;
            notes?: string;
        };
        TransmissionNode: {
            /** Format: uuid */
            node_id: string;
            /** @enum {string} */
            node_type: "INGEST" | "EXTRACT" | "NORMALIZE" | "RECONCILE" | "CALCULATE" | "INFER" | "HUMAN_VERIFY" | "EXPORT";
            /** @enum {string} */
            actor_type: "AGENT" | "HUMAN" | "SYSTEM";
            actor_id: string;
            input_refs?: {
                [key: string]: unknown;
            }[];
            output_refs?: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            timestamp: string;
            confidence?: number | null;
            dhabt_score?: number | null;
            /** @enum {string|null} */
            verification_method?: "auto" | "cross-check" | "human-verified" | null;
            notes?: string | null;
        };
        Sanad: {
            /** Format: uuid */
            sanad_id: string;
            /** Format: uuid */
            claim_id: string;
            /** Format: uuid */
            deal_id: string;
            /** Format: uuid */
            primary_evidence_id: string;
            corroborating_evidence_ids?: string[];
            transmission_chain: components["schemas"]["TransmissionNode"][];
            computed: {
                grade: components["schemas"]["SanadGrade"];
                grade_rationale?: string;
                corroboration_level: components["schemas"]["CorroborationLevel"];
                independent_chain_count: number;
            };
        };
        Defect: {
            /** Format: uuid */
            defect_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            claim_id?: string | null;
            /** Format: uuid */
            deal_id?: string | null;
            /** @enum {string} */
            defect_type: "BROKEN_CHAIN" | "MISSING_LINK" | "UNKNOWN_SOURCE" | "CONCEALMENT" | "INCONSISTENCY" | "ANOMALY_VS_STRONGER_SOURCES" | "CHRONO_IMPOSSIBLE" | "CHAIN_GRAFTING" | "CIRCULARITY" | "STALENESS" | "UNIT_MISMATCH" | "TIME_WINDOW_MISMATCH" | "SCOPE_DRIFT" | "IMPLAUSIBILITY_REQUIRES_PROOF";
            severity: components["schemas"]["DefectSeverity"];
            description: string;
            cure_protocol: string;
            /** @enum {string} */
            status: "OPEN" | "CURED" | "WAIVED";
            waiver_reason?: string | null;
            waived_by?: string | null;
            /** Format: date-time */
            waived_at?: string | null;
            cured_by?: string | null;
            cured_reason?: string | null;
            /** Format: date-time */
            cured_at?: string | null;
            affected_claim_ids?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        CreateDefectRequest: {
            /** Format: uuid */
            claim_id?: string;
            defect_type: string;
            severity?: string;
            description: string;
            cure_protocol: string;
        };
        WaiveDefectRequest: {
            actor: string;
            reason: string;
        };
        CureDefectRequest: {
            actor: string;
            reason: string;
        };
        CreateSanadRequest: {
            /** Format: uuid */
            claim_id: string;
            /** Format: uuid */
            primary_evidence_id: string;
            corroborating_evidence_ids?: string[];
            transmission_chain?: components["schemas"]["TransmissionNode"][];
            /** @default 0.9 */
            extraction_confidence: number;
        };
        UpdateSanadRequest: {
            corroborating_evidence_ids?: string[];
            transmission_chain?: components["schemas"]["TransmissionNode"][];
        };
        SetCorroborationRequest: {
            corroborating_evidence_ids: string[];
        };
        PaginatedSanadList: {
            items: components["schemas"]["Sanad"][];
            next_cursor?: string | null;
        };
        RunRef: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
        };
        StartRunRequest: {
            /** @enum {string} */
            mode: "SNAPSHOT" | "FULL";
        };
        RunStatus: {
            /** Format: uuid */
            run_id: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        RunCalcRequest: {
            calc_name: string;
        };
        StartDebateRequest: {
            protocol_version: string;
            /** @default 5 */
            max_rounds: number;
        };
        DebateSession: {
            /** Format: uuid */
            debate_id: string;
            /** Format: uuid */
            deal_id: string;
            protocol_version: string;
            rounds?: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            created_at: string;
        };
        HumanGate: {
            /** Format: uuid */
            gate_id: string;
            /** Format: uuid */
            deal_id: string;
            gate_type: string;
            status: string;
            /** Format: date-time */
            created_at: string;
        };
        SubmitHumanGateActionRequest: {
            /** Format: uuid */
            gate_id: string;
            action: string;
            notes?: string;
        };
        HumanGateAction: {
            /** Format: uuid */
            action_id: string;
            /** Format: uuid */
            gate_id: string;
            action: string;
            actor_id: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateOverrideRequest: {
            override_type: string;
            justification: string;
        };
        Override: {
            /** Format: uuid */
            override_id: string;
            /** Format: uuid */
            deal_id: string;
            override_type: string;
            justification: string;
            status: string;
            /** Format: date-time */
            created_at: string;
        };
        GenerateDeliverableRequest: {
            deliverable_type: string;
            /**
             * @default PDF
             * @enum {string}
             */
            format: "PDF" | "DOCX" | "JSON";
        };
        Deliverable: {
            /** Format: uuid */
            deliverable_id: string;
            /** Format: uuid */
            deal_id: string;
            deliverable_type: string;
            status: string;
            uri?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        AuditEvent: {
            /** Format: uuid */
            event_id: string;
            event_type: string;
            /** Format: date-time */
            occurred_at: string;
        };
        CreateWebhookRequest: {
            url: string;
            events: string[];
            secret?: string | null;
            /** @default true */
            active: boolean;
        };
        Webhook: {
            /** Format: uuid */
            webhook_id: string;
            url: string;
            events: string[];
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        Integration: {
            integration_id: string;
            name: string;
            category: string;
            status: string;
        };
        IntegrationList: {
            items: components["schemas"]["Integration"][];
        };
        PaginatedDealList: {
            items: components["schemas"]["Deal"][];
            next_cursor?: string | null;
        };
        PaginatedDocumentList: {
            items: components["schemas"]["DocumentArtifact"][];
            next_cursor?: string | null;
        };
        PaginatedClaimList: {
            items: components["schemas"]["Claim"][];
            next_cursor?: string | null;
        };
        PaginatedDefectList: {
            items: components["schemas"]["Defect"][];
            next_cursor?: string | null;
        };
        PaginatedCalcList: {
            items: Record<string, never>[];
            next_cursor?: string | null;
        };
        PaginatedHumanGateList: {
            items: components["schemas"]["HumanGate"][];
            next_cursor?: string | null;
        };
        PaginatedDeliverableList: {
            items: components["schemas"]["Deliverable"][];
            next_cursor?: string | null;
        };
        PaginatedAuditEventList: {
            items: components["schemas"]["AuditEvent"][];
            next_cursor?: string | null;
        };
        TruthDashboardSummary: {
            /** @description Total number of claims for this deal */
            total_claims: number;
            /** @description Count of claims by Sanad grade */
            by_grade: {
                A: number;
                B: number;
                C: number;
                D: number;
            };
            /** @description Count of claims by verdict */
            by_verdict: {
                VERIFIED: number;
                INFLATED: number;
                CONTRADICTED: number;
                UNVERIFIED: number;
                SUBJECTIVE: number;
            };
            /** @description Count of fatal defects affecting claims in this deal */
            fatal_defects: number;
        };
        TruthDashboard: {
            /**
             * Format: uuid
             * @description UUID of the deal
             */
            deal_id: string;
            summary: components["schemas"]["TruthDashboardSummary"];
            claims: components["schemas"]["PaginatedClaimList"];
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict / Idempotency collision */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        DealId: string;
        DocId: string;
        ClaimId: string;
        RunId: string;
        DebateId: string;
        DefectId: string;
        SanadId: string;
        Limit: number;
        Cursor: string;
        /** @description Idempotency key for safe retries on POST/PATCH operations. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** Format: date-time */
                        time?: string;
                        /** @example 6.3 */
                        version?: string;
                    };
                };
            };
        };
    };
    getTenantMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantContext"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDeals: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                status?: components["schemas"]["DealStatus"];
                stage?: components["schemas"]["DealStage"];
                /** @description Full-text search (name, company, tags) */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deal list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDealList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDeal: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDealRequest"];
            };
        };
        responses: {
            /** @description Deal created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getDeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDeal: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDealRequest"];
            };
        };
        responses: {
            /** @description Updated deal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getDealTruthDashboard: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Truth dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruthDashboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDealDocuments: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createDealDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description Document created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentArtifact"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    ingestDocument: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                docId: components["parameters"]["DocId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @default NORMAL
                     * @enum {string}
                     */
                    priority?: "LOW" | "NORMAL" | "HIGH";
                };
            };
        };
        responses: {
            /** @description Ingestion started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDealClaims: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                verdict?: components["schemas"]["ClaimVerdict"];
                grade?: components["schemas"]["SanadGrade"];
                materiality?: components["schemas"]["Materiality"];
            };
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claim list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedClaimList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createClaim: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClaimRequest"];
            };
        };
        responses: {
            /** @description Claim created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getClaim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claimId: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claim */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateClaim: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                claimId: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClaimRequest"];
            };
        };
        responses: {
            /** @description Updated claim */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Claim"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getClaimSanad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claimId: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanad chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sanad"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDealDefects: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                severity?: components["schemas"]["DefectSeverity"];
            };
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Defect list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDefectList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createDefect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDefectRequest"];
            };
        };
        responses: {
            /** @description Created defect */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Defect"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listClaimDefects: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                claimId: components["parameters"]["ClaimId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Defect list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDefectList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDefect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                defect_id: components["parameters"]["DefectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Defect details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Defect"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    waiveDefect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                defect_id: components["parameters"]["DefectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaiveDefectRequest"];
            };
        };
        responses: {
            /** @description Waived defect */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Defect"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cureDefect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                defect_id: components["parameters"]["DefectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CureDefectRequest"];
            };
        };
        responses: {
            /** @description Cured defect */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Defect"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDealSanads: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanad list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSanadList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createSanad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSanadRequest"];
            };
        };
        responses: {
            /** @description Created sanad */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sanad"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSanad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sanad_id: components["parameters"]["SanadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanad details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sanad"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSanad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sanad_id: components["parameters"]["SanadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSanadRequest"];
            };
        };
        responses: {
            /** @description Updated sanad */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sanad"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    setSanadCorroboration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sanad_id: components["parameters"]["SanadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCorroborationRequest"];
            };
        };
        responses: {
            /** @description Updated sanad with new grade */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sanad"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDealCalcs: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calc list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCalcList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    runCalc: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCalcRequest"];
            };
        };
        responses: {
            /** @description Calc run started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Run started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    startDebate: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartDebateRequest"];
            };
        };
        responses: {
            /** @description Debate started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getDebate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debateId: components["parameters"]["DebateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Debate session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebateSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listHumanGates: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human gates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHumanGateList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    submitHumanGateAction: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitHumanGateActionRequest"];
            };
        };
        responses: {
            /** @description Human gate action recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanGateAction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createOverride: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOverrideRequest"];
            };
        };
        responses: {
            /** @description Override created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Override"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listDeliverables: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deliverables list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDeliverableList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    generateDeliverable: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                dealId: components["parameters"]["DealId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateDeliverableRequest"];
            };
        };
        responses: {
            /** @description Deliverable generation started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
                dealId?: string;
                eventType?: string;
                after?: string;
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuditEventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integrations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: {
                /** @description Idempotency key for safe retries on POST/PATCH operations. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookRequest"];
            };
        };
        responses: {
            /** @description Webhook created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
